// Package svg do not edit, this file was autogenerated.
package svg

import tags "github.com/Nevoral/LuxeGoUI/Tags"

/*
A - Indicate links (also known as hyperlinks or Web links). An "a’ element forms a link if it has a "href’ or "xlink:href’ attribute; without these attributes the "a’ element is an inactive placeholder for a link.
Indicate links (also known as hyperlinks or Web links). An "a’ element forms a link if it has a "href’ or "xlink:href’ attribute; without these attributes the "a’ element is an inactive placeholder for a link.
*/
func A(content ...any) *tags.ATagSvg {
	return tags.ASvg(content)
}

/*
Animate -
*/
func Animate() *tags.AnimateTagSvg {
	return tags.AnimateSvg()
}

/*
AnimateMotion -
*/
func AnimateMotion() *tags.AnimateMotionTagSvg {
	return tags.AnimateMotionSvg()
}

/*
AnimateTransform -
*/
func AnimateTransform() *tags.AnimateTransformTagSvg {
	return tags.AnimateTransformSvg()
}

/*
Circle -
*/
func Circle() *tags.CircleTagSvg {
	return tags.CircleSvg()
}

/*
ClipPath -
*/
func ClipPath(content ...any) *tags.ClipPathTagSvg {
	return tags.ClipPathSvg(content)
}

/*
Defs -
*/
func Defs(content ...any) *tags.DefsTagSvg {
	return tags.DefsSvg(content)
}

/*
Desc -
*/
func Desc(content ...any) *tags.DescTagSvg {
	return tags.DescSvg(content)
}

/*
Discard -
*/
func Discard(content ...any) *tags.DiscardTagSvg {
	return tags.DiscardSvg(content)
}

/*
Ellipse -
*/
func Ellipse() *tags.EllipseTagSvg {
	return tags.EllipseSvg()
}

/*
FeBlend -
*/
func FeBlend() *tags.FeBlendTagSvg {
	return tags.FeBlendSvg()
}

/*
FeColorMatrix -
*/
func FeColorMatrix() *tags.FeColorMatrixTagSvg {
	return tags.FeColorMatrixSvg()
}

/*
FeComponentTransfer -
*/
func FeComponentTransfer() *tags.FeComponentTransferTagSvg {
	return tags.FeComponentTransferSvg()
}

/*
FeComposite -
*/
func FeComposite() *tags.FeCompositeTagSvg {
	return tags.FeCompositeSvg()
}

/*
FeConvolveMatrix -
*/
func FeConvolveMatrix() *tags.FeConvolveMatrixTagSvg {
	return tags.FeConvolveMatrixSvg()
}

/*
FeDiffuseLighting -
*/
func FeDiffuseLighting() *tags.FeDiffuseLightingTagSvg {
	return tags.FeDiffuseLightingSvg()
}

/*
FeDisplacementMap -
*/
func FeDisplacementMap() *tags.FeDisplacementMapTagSvg {
	return tags.FeDisplacementMapSvg()
}

/*
FeDistantLight -
*/
func FeDistantLight() *tags.FeDistantLightTagSvg {
	return tags.FeDistantLightSvg()
}

/*
FeDropShadow -
*/
func FeDropShadow() *tags.FeDropShadowTagSvg {
	return tags.FeDropShadowSvg()
}

/*
FeFlood -
*/
func FeFlood() *tags.FeFloodTagSvg {
	return tags.FeFloodSvg()
}

/*
FeFuncA -
*/
func FeFuncA() *tags.FeFuncATagSvg {
	return tags.FeFuncASvg()
}

/*
FeFuncB -
*/
func FeFuncB() *tags.FeFuncBTagSvg {
	return tags.FeFuncBSvg()
}

/*
FeFuncG -
*/
func FeFuncG() *tags.FeFuncGTagSvg {
	return tags.FeFuncGSvg()
}

/*
FeFuncR -
*/
func FeFuncR() *tags.FeFuncRTagSvg {
	return tags.FeFuncRSvg()
}

/*
FeGaussianBlur -
*/
func FeGaussianBlur() *tags.FeGaussianBlurTagSvg {
	return tags.FeGaussianBlurSvg()
}

/*
FeImage -
*/
func FeImage() *tags.FeImageTagSvg {
	return tags.FeImageSvg()
}

/*
FeMerge -
*/
func FeMerge(content ...any) *tags.FeMergeTagSvg {
	return tags.FeMergeSvg(content)
}

/*
FeMergeNode -
*/
func FeMergeNode() *tags.FeMergeNodeTagSvg {
	return tags.FeMergeNodeSvg()
}

/*
FeMorphology -
*/
func FeMorphology() *tags.FeMorphologyTagSvg {
	return tags.FeMorphologySvg()
}

/*
FeOffset -
*/
func FeOffset() *tags.FeOffsetTagSvg {
	return tags.FeOffsetSvg()
}

/*
FePointLight -
*/
func FePointLight() *tags.FePointLightTagSvg {
	return tags.FePointLightSvg()
}

/*
FeSpecularLighting -
*/
func FeSpecularLighting() *tags.FeSpecularLightingTagSvg {
	return tags.FeSpecularLightingSvg()
}

/*
FeSpotLight -
*/
func FeSpotLight() *tags.FeSpotLightTagSvg {
	return tags.FeSpotLightSvg()
}

/*
FeTile -
*/
func FeTile() *tags.FeTileTagSvg {
	return tags.FeTileSvg()
}

/*
FeTurbulence -
*/
func FeTurbulence() *tags.FeTurbulenceTagSvg {
	return tags.FeTurbulenceSvg()
}

/*
Filter -
*/
func Filter(content ...any) *tags.FilterTagSvg {
	return tags.FilterSvg(content)
}

/*
ForeignObject -
*/
func ForeignObject(content ...any) *tags.ForeignObjectTagSvg {
	return tags.ForeignObjectSvg(content)
}

/*
G -
*/
func G(content ...any) *tags.GTagSvg {
	return tags.GSvg(content)
}

/*
Hatch -
*/
func Hatch(content ...any) *tags.HatchTagSvg {
	return tags.HatchSvg(content)
}

/*
Hatchpath -
*/
func Hatchpath(content ...any) *tags.HatchpathTagSvg {
	return tags.HatchpathSvg(content)
}

/*
Image -
*/
func Image() *tags.ImageTagSvg {
	return tags.ImageSvg()
}

/*
Line -
*/
func Line() *tags.LineTagSvg {
	return tags.LineSvg()
}

/*
LinearGradient -
*/
func LinearGradient(content ...any) *tags.LinearGradientTagSvg {
	return tags.LinearGradientSvg(content)
}

/*
Marker -
*/
func Marker(content ...any) *tags.MarkerTagSvg {
	return tags.MarkerSvg(content)
}

/*
Mask -
*/
func Mask(content ...any) *tags.MaskTagSvg {
	return tags.MaskSvg(content)
}

/*
Metadata -
*/
func Metadata(content ...any) *tags.MetadataTagSvg {
	return tags.MetadataSvg(content)
}

/*
Mpath -
*/
func Mpath(content ...any) *tags.MpathTagSvg {
	return tags.MpathSvg(content)
}

/*
Path -
*/
func Path() *tags.PathTagSvg {
	return tags.PathSvg()
}

/*
Pattern -
*/
func Pattern(content ...any) *tags.PatternTagSvg {
	return tags.PatternSvg(content)
}

/*
Polygon -
*/
func Polygon() *tags.PolygonTagSvg {
	return tags.PolygonSvg()
}

/*
Polyline -
*/
func Polyline() *tags.PolylineTagSvg {
	return tags.PolylineSvg()
}

/*
RadialGradient -
*/
func RadialGradient(content ...any) *tags.RadialGradientTagSvg {
	return tags.RadialGradientSvg(content)
}

/*
Rect -
*/
func Rect() *tags.RectTagSvg {
	return tags.RectSvg()
}

/*
Script -
*/
func Script(content ...any) *tags.ScriptTagSvg {
	return tags.ScriptSvg(content)
}

/*
Set -
*/
func Set(content ...any) *tags.SetTagSvg {
	return tags.SetSvg(content)
}

/*
Stop -
*/
func Stop() *tags.StopTagSvg {
	return tags.StopSvg()
}

/*
Style -
*/
func Style(content ...any) *tags.StyleTagSvg {
	return tags.StyleSvg(content)
}

/*
Svg -
*/
func Svg(content ...any) *tags.SvgTagSvg {
	return tags.SvgSvg(content)
}

/*
Switch -
*/
func Switch(content ...any) *tags.SwitchTagSvg {
	return tags.SwitchSvg(content)
}

/*
Symbol -
*/
func Symbol(content ...any) *tags.SymbolTagSvg {
	return tags.SymbolSvg(content)
}

/*
Text -
*/
func Text(content ...any) *tags.TextTagSvg {
	return tags.TextSvg(content)
}

/*
TextPath -
*/
func TextPath() *tags.TextPathTagSvg {
	return tags.TextPathSvg()
}

/*
Title -
*/
func Title(content ...any) *tags.TitleTagSvg {
	return tags.TitleSvg(content)
}

/*
Tspan -
*/
func Tspan() *tags.TspanTagSvg {
	return tags.TspanSvg()
}

/*
Use -
*/
func Use() *tags.UseTagSvg {
	return tags.UseSvg()
}

/*
View -
*/
func View(content ...any) *tags.ViewTagSvg {
	return tags.ViewSvg(content)
}
