// Package tags do not edit, this file was autogenerated.
package tags

import spec "github.com/Nevoral/LuxeGoUI/Specification"

func AnimateSvg() *AnimateTagSvg {
	return &AnimateTagSvg{
		tag: &tag{
			name:                "animate",
			attributes:          nil,
			supportedAttributes: nil,
			tagType:             spec.SelfClosingType,
			namespace:           spec.SVG,
			children:            nil,
			textContent:         "",
			parent:              nil,
			nestingLevel:        0,
			renderFormat:        DefaultHtml,
		},
	}
}

type AnimateTagSvg struct {
	*tag
}

/*
************************************************************************************************************************
*-------------------------------------------------- Extension Method --------------------------------------------------*
************************************************************************************************************************
 */

/*
CustomAttribute - This is method for adding custom attribute, that are not in HTML5 specification.
*/
func (a *AnimateTagSvg) CustomAttribute(attributes ...*Attribute) *AnimateTagSvg {
	a.registerAttributes(attributes...)
	return a
}

/*
************************************************************************************************************************
*------------------------------------------------ Specific Attributes -------------------------------------------------*
************************************************************************************************************************
 */

/*
Accumulate -
*/
func (a *AnimateTagSvg) Accumulate(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("accumulate", value)
	return a
}

/*
Additive -
*/
func (a *AnimateTagSvg) Additive(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("additive", value)
	return a
}

/*
AttributeName -
*/
func (a *AnimateTagSvg) AttributeName(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("attributeName", value)
	return a
}

/*
AttributeType -
*/
func (a *AnimateTagSvg) AttributeType(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("attributeType", value)
	return a
}

/*
Begin -
*/
func (a *AnimateTagSvg) Begin(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("begin", value)
	return a
}

/*
By -
*/
func (a *AnimateTagSvg) By(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("by", value)
	return a
}

/*
CalcMode -
*/
func (a *AnimateTagSvg) CalcMode(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("calcMode", value)
	return a
}

/*
Dur -
*/
func (a *AnimateTagSvg) Dur(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("dur", value)
	return a
}

/*
End -
*/
func (a *AnimateTagSvg) End(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("end", value)
	return a
}

/*
Fill -
*/
func (a *AnimateTagSvg) Fill(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("fill", value)
	return a
}

/*
From -
*/
func (a *AnimateTagSvg) From(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("from", value)
	return a
}

/*
KeySplines -
*/
func (a *AnimateTagSvg) KeySplines(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("keySplines", value)
	return a
}

/*
KeyTimes -
*/
func (a *AnimateTagSvg) KeyTimes(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("keyTimes", value)
	return a
}

/*
Max -
*/
func (a *AnimateTagSvg) Max(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("max", value)
	return a
}

/*
Min -
*/
func (a *AnimateTagSvg) Min(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("min", value)
	return a
}

/*
Remove -
*/
func (a *AnimateTagSvg) Remove(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("remove", value)
	return a
}

/*
RepeatCount -
*/
func (a *AnimateTagSvg) RepeatCount(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("repeatCount", value)
	return a
}

/*
RepeatDur -
*/
func (a *AnimateTagSvg) RepeatDur(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("repeatDur", value)
	return a
}

/*
Restart -
*/
func (a *AnimateTagSvg) Restart(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("restart", value)
	return a
}

/*
To -
*/
func (a *AnimateTagSvg) To(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("to", value)
	return a
}

/*
Values -
*/
func (a *AnimateTagSvg) Values(value string) *AnimateTagSvg {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("values", value)
	return a
}
