// Package tags do not edit, this file was autogenerated.
package tags

import spec "github.com/Nevoral/LuxeGoUI/Specification"

func AreaHtml() *AreaTagHtml {
	return &AreaTagHtml{
		tag: &tag{
			name:                "area",
			attributes:          nil,
			supportedAttributes: nil,
			tagType:             spec.SelfClosingType,
			namespace:           spec.HTML,
			children:            nil,
			textContent:         "",
			parent:              nil,
			nestingLevel:        0,
			renderFormat:        DefaultHtml,
		},
	}
}

type AreaTagHtml struct {
	*tag
}

/*
************************************************************************************************************************
*-------------------------------------------------- Extension Method --------------------------------------------------*
************************************************************************************************************************
 */

/*
CustomAttribute - This is method for adding custom attribute, that are not in HTML5 specification.
*/
func (a *AreaTagHtml) CustomAttribute(attributes ...*Attribute) *AreaTagHtml {
	a.registerAttributes(attributes...)
	return a
}

/*
************************************************************************************************************************
*------------------------------------------------ Specific Attributes -------------------------------------------------*
************************************************************************************************************************
 */

/*
Alt - A text string alternative to display on browsers that do not display images. The text should be phrased so that it presents the user with the same kind of choice as the image would offer when displayed without the alternative text. This attribute is required only if the href attribute is used.
A text string alternative to display on browsers that do not display images. The text should be phrased so that it presents the user with the same kind of choice as the image would offer when displayed without the alternative text. This attribute is required only if the href attribute is used.
*/
func (a *AreaTagHtml) Alt(value string) *AreaTagHtml {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("alt", value)
	return a
}

/*
Coords - The coords attribute details the coordinates of the shape attribute in size, shape, and placement of an <area>. This attribute must not be used if shape is set to default.
The coords attribute details the coordinates of the shape attribute in size, shape, and placement of an <area>. This attribute must not be used if shape is set to default.

	    rect: the value is x1,y1,x2,y2. The value specifies the coordinates of the top-left and bottom-right corner of the rectangle. For example, in <area shape="rect" coords="0,0,253,27" href="#" target="_blank" alt="Mozilla"> the coordinates are 0,0 and 253,27, indicating the top-left and bottom-right corners of the rectangle, respectively.
	    circle: the value is x,y,radius. Value specifies the coordinates of the circle center and the radius. For example: <area shape="circle" coords="130,136,60" href="#" target="_blank" alt="MDN">
	    poly: the value is x1,y1,x2,y2,..,xn,yn. Value specifies the coordinates of the edges of the polygon. If the first and last coordinate pairs are not the same, the browser will add the last coordinate pair to close the polygon

	The values are numbers of CSS pixels.
*/
func (a *AreaTagHtml) Coords(value string) *AreaTagHtml {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("coords", value)
	return a
}

/*
Download - This attribute, if present, indicates that the author intends the hyperlink to be used for downloading a resource. See <a> for a full description of the download attribute.
This attribute, if present, indicates that the author intends the hyperlink to be used for downloading a resource. See <a> for a full description of the download attribute.
*/
func (a *AreaTagHtml) Download(value string) *AreaTagHtml {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("download", value)
	return a
}

/*
Href - The hyperlink target for the area. Its value is a valid URL. This attribute may be omitted; if so, the <area> element does not represent a hyperlink.
The hyperlink target for the area. Its value is a valid URL. This attribute may be omitted; if so, the <area> element does not represent a hyperlink.
*/
func (a *AreaTagHtml) Href(value string) *AreaTagHtml {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("href", value)
	return a
}

/*
Ping - Contains a space-separated list of URLs to which, when the hyperlink is followed, POST requests with the body PING will be sent by the browser (in the background). Typically used for tracking.
Contains a space-separated list of URLs to which, when the hyperlink is followed, POST requests with the body PING will be sent by the browser (in the background). Typically used for tracking.
*/
func (a *AreaTagHtml) Ping(value string) *AreaTagHtml {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("ping", value)
	return a
}

/*
Referrerpolicy - A string indicating which referrer to use when fetching the resource:
A string indicating which referrer to use when fetching the resource:

	no-referrer: The Referer header will not be sent.
	no-referrer-when-downgrade: The Referer header will not be sent to origins without TLS (HTTPS).
	origin: The sent referrer will be limited to the origin of the referring page: its scheme, host, and port.
	origin-when-cross-origin: The referrer sent to other origins will be limited to the scheme, the host, and the port. Navigations on the same origin will still include the path.
	same-origin: A referrer will be sent for same origin, but cross-origin requests will contain no referrer information.
	strict-origin: Only send the origin of the document as the referrer when the protocol security level stays the same (HTTPS→HTTPS), but don't send it to a less secure destination (HTTPS→HTTP).
	strict-origin-when-cross-origin (default): Send a full URL when performing a same-origin request, only send the origin when the protocol security level stays the same (HTTPS→HTTPS), and send no header to a less secure destination (HTTPS→HTTP).
	unsafe-url: The referrer will include the origin and the path (but not the fragment, password, or username). This value is unsafe, because it leaks origins and paths from TLS-protected resources to insecure origins.
*/
func (a *AreaTagHtml) Referrerpolicy(value string) *AreaTagHtml {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("referrerpolicy", value)
	return a
}

/*
Rel - For anchors containing the href attribute, this attribute specifies the relationship of the target object to the link object. The value is a space-separated list of link types. The values and their semantics will be registered by some authority that might have meaning to the document author. The default relationship, if no other is given, is void. Use this attribute only if the href attribute is present.
For anchors containing the href attribute, this attribute specifies the relationship of the target object to the link object. The value is a space-separated list of link types. The values and their semantics will be registered by some authority that might have meaning to the document author. The default relationship, if no other is given, is void. Use this attribute only if the href attribute is present.
*/
func (a *AreaTagHtml) Rel(value string) *AreaTagHtml {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("rel", value)
	return a
}

/*
Shape - The shape of the associated hot spot. The specifications for HTML defines the values rect, which defines a rectangular region; circle, which defines a circular region; poly, which defines a polygon; and default, which indicates the entire region beyond any defined shapes.
The shape of the associated hot spot. The specifications for HTML defines the values rect, which defines a rectangular region; circle, which defines a circular region; poly, which defines a polygon; and default, which indicates the entire region beyond any defined shapes.
*/
func (a *AreaTagHtml) Shape(value string) *AreaTagHtml {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("shape", value)
	return a
}

/*
Target - A keyword or author-defined name of the browsing context to display the linked resource. The following keywords have special meanings:
A keyword or author-defined name of the browsing context to display the linked resource. The following keywords have special meanings:

	    _self (default): Show the resource in the current browsing context.
	    _blank: Show the resource in a new, unnamed browsing context.
	    _parent: Show the resource in the parent browsing context of the current one, if the current page is inside a frame. If there is no parent, acts the same as _self.
	    _top: Show the resource in the topmost browsing context (the browsing context that is an ancestor of the current one and has no parent). If there is no parent, acts the same as _self.

	Use this attribute only if the href attribute is present.

	Note: Setting target="_blank" on <area> elements implicitly provides the same rel behavior as setting rel="noopener" which does not set window.opener. See browser compatibility for support status.
*/
func (a *AreaTagHtml) Target(value string) *AreaTagHtml {
	if a.attributes == nil {
		a.attributes = []*Attribute{}
	}
	a.registerAttribute("target", value)
	return a
}
