// Package tags do not edit, this file was autogenerated.
package tags

import (
	"fmt"
	spec "github.com/Nevoral/LuxeGoUI/Specification"
)

func CodeHtml(tags []any) *CodeTagHtml {
	node := &CodeTagHtml{
		tag: &tag{
			name:                "code",
			attributes:          nil,
			supportedAttributes: nil,
			tagType:             spec.FullTagType,
			namespace:           spec.HTML,
			children:            nil,
			textContent:         "",
			parent:              nil,
			nestingLevel:        0,
			renderFormat:        DefaultHtml,
		},
	}
	return node.supportedChildrenCheck(tags)
}

type CodeTagHtml struct {
	*tag
}

/*
************************************************************************************************************************
*-------------------------------------------------- Extension Method --------------------------------------------------*
************************************************************************************************************************
 */

/*
CustomAttribute - This is method for adding custom attribute, that are not in HTML5 specification.
*/
func (c *CodeTagHtml) CustomAttribute(attributes ...*Attribute) *CodeTagHtml {
	c.registerAttributes(attributes...)
	return c
}

/*
Children - Method for nesting tags into parent tag
*/
func (c *CodeTagHtml) Children(tags ...any) *CodeTagHtml {
	return c.supportedChildrenCheck(tags)
}

func (c *CodeTagHtml) supportedChildrenCheck(tags []any) *CodeTagHtml {
	for _, tagObj := range tags {
		switch val := tagObj.(type) {
		case string:
			c.registerChildren(TextContentSvg(val).getTag())
		case content:
			c.registerChildren(val.getTag())
		case []content:
			for _, child := range val {
				c.registerChildren(child.getTag())
			}
		default:
			panic(fmt.Sprintf("Unsupported content type. %v", val))
		}
	}
	return c
}

/*
************************************************************************************************************************
*------------------------------------------------ Specific Attributes -------------------------------------------------*
************************************************************************************************************************
 */
