// Package tags do not edit, this file was autogenerated.
package tags

import (
	"fmt"
	spec "github.com/Nevoral/LuxeGoUI/Specification"
)

func DetailsHtml(tags []any) *DetailsTagHtml {
	node := &DetailsTagHtml{
		tag: &tag{
			name:                "details",
			attributes:          nil,
			supportedAttributes: nil,
			tagType:             spec.FullTagType,
			namespace:           spec.HTML,
			children:            nil,
			textContent:         "",
			parent:              nil,
			nestingLevel:        0,
			renderFormat:        DefaultHtml,
		},
	}
	return node.supportedChildrenCheck(tags)
}

type DetailsTagHtml struct {
	*tag
}

/*
************************************************************************************************************************
*-------------------------------------------------- Extension Method --------------------------------------------------*
************************************************************************************************************************
 */

/*
CustomAttribute - This is method for adding custom attribute, that are not in HTML5 specification.
*/
func (d *DetailsTagHtml) CustomAttribute(attributes ...*Attribute) *DetailsTagHtml {
	d.registerAttributes(attributes...)
	return d
}

/*
Children - Method for nesting tags into parent tag
*/
func (d *DetailsTagHtml) Children(tags ...any) *DetailsTagHtml {
	return d.supportedChildrenCheck(tags)
}

func (d *DetailsTagHtml) supportedChildrenCheck(tags []any) *DetailsTagHtml {
	for _, tagObj := range tags {
		switch val := tagObj.(type) {
		case string:
			d.registerChildren(TextContentSvg(val).getTag())
		case content:
			d.registerChildren(val.getTag())
		case []content:
			for _, child := range val {
				d.registerChildren(child.getTag())
			}
		default:
			panic(fmt.Sprintf("Unsupported content type. %v", val))
		}
	}
	return d
}

/*
************************************************************************************************************************
*------------------------------------------------ Specific Attributes -------------------------------------------------*
************************************************************************************************************************
 */

/*
Open -
*/
func (d *DetailsTagHtml) Open() *DetailsTagHtml {
	if d.attributes == nil {
		d.attributes = []*Attribute{}
	}
	d.registerAttribute("open", "")
	return d
}
