// Package tags do not edit, this file was autogenerated.
package tags

import spec "github.com/Nevoral/LuxeGoUI/Specification"

func FeOffsetSvg() *FeOffsetTagSvg {
	return &FeOffsetTagSvg{
		tag: &tag{
			name:                "feOffset",
			attributes:          nil,
			supportedAttributes: nil,
			tagType:             spec.SelfClosingType,
			namespace:           spec.SVG,
			children:            nil,
			textContent:         "",
			parent:              nil,
			nestingLevel:        0,
			renderFormat:        DefaultHtml,
		},
	}
}

type FeOffsetTagSvg struct {
	*tag
}

/*
************************************************************************************************************************
*-------------------------------------------------- Extension Method --------------------------------------------------*
************************************************************************************************************************
 */

/*
CustomAttribute - This is method for adding custom attribute, that are not in HTML5 specification.
*/
func (f *FeOffsetTagSvg) CustomAttribute(attributes ...*Attribute) *FeOffsetTagSvg {
	f.registerAttributes(attributes...)
	return f
}

/*
************************************************************************************************************************
*------------------------------------------------ Specific Attributes -------------------------------------------------*
************************************************************************************************************************
 */

/*
Dx -
*/
func (f *FeOffsetTagSvg) Dx(value string) *FeOffsetTagSvg {
	if f.attributes == nil {
		f.attributes = []*Attribute{}
	}
	f.registerAttribute("dx", value)
	return f
}

/*
Dy -
*/
func (f *FeOffsetTagSvg) Dy(value string) *FeOffsetTagSvg {
	if f.attributes == nil {
		f.attributes = []*Attribute{}
	}
	f.registerAttribute("dy", value)
	return f
}

/*
In -
*/
func (f *FeOffsetTagSvg) In(value string) *FeOffsetTagSvg {
	if f.attributes == nil {
		f.attributes = []*Attribute{}
	}
	f.registerAttribute("in", value)
	return f
}
