// Package tags do not edit, this file was autogenerated.
package tags

import spec "github.com/Nevoral/LuxeGoUI/Specification"

func FeSpotLightSvg() *FeSpotLightTagSvg {
	return &FeSpotLightTagSvg{
		tag: &tag{
			name:                "feSpotLight",
			attributes:          nil,
			supportedAttributes: nil,
			tagType:             spec.SelfClosingType,
			namespace:           spec.SVG,
			children:            nil,
			textContent:         "",
			parent:              nil,
			nestingLevel:        0,
			renderFormat:        DefaultHtml,
		},
	}
}

type FeSpotLightTagSvg struct {
	*tag
}

/*
************************************************************************************************************************
*-------------------------------------------------- Extension Method --------------------------------------------------*
************************************************************************************************************************
 */

/*
CustomAttribute - This is method for adding custom attribute, that are not in HTML5 specification.
*/
func (f *FeSpotLightTagSvg) CustomAttribute(attributes ...*Attribute) *FeSpotLightTagSvg {
	f.registerAttributes(attributes...)
	return f
}

/*
************************************************************************************************************************
*------------------------------------------------ Specific Attributes -------------------------------------------------*
************************************************************************************************************************
 */

/*
LimitingConeAngle -
*/
func (f *FeSpotLightTagSvg) LimitingConeAngle(value string) *FeSpotLightTagSvg {
	if f.attributes == nil {
		f.attributes = []*Attribute{}
	}
	f.registerAttribute("limitingConeAngle", value)
	return f
}

/*
PointsAtX -
*/
func (f *FeSpotLightTagSvg) PointsAtX(value string) *FeSpotLightTagSvg {
	if f.attributes == nil {
		f.attributes = []*Attribute{}
	}
	f.registerAttribute("pointsAtX", value)
	return f
}

/*
PointsAtY -
*/
func (f *FeSpotLightTagSvg) PointsAtY(value string) *FeSpotLightTagSvg {
	if f.attributes == nil {
		f.attributes = []*Attribute{}
	}
	f.registerAttribute("pointsAtY", value)
	return f
}

/*
PointsAtZ -
*/
func (f *FeSpotLightTagSvg) PointsAtZ(value string) *FeSpotLightTagSvg {
	if f.attributes == nil {
		f.attributes = []*Attribute{}
	}
	f.registerAttribute("pointsAtZ", value)
	return f
}

/*
SpecularExponent -
*/
func (f *FeSpotLightTagSvg) SpecularExponent(value string) *FeSpotLightTagSvg {
	if f.attributes == nil {
		f.attributes = []*Attribute{}
	}
	f.registerAttribute("specularExponent", value)
	return f
}

/*
X -
*/
func (f *FeSpotLightTagSvg) X(value string) *FeSpotLightTagSvg {
	if f.attributes == nil {
		f.attributes = []*Attribute{}
	}
	f.registerAttribute("x", value)
	return f
}

/*
Y -
*/
func (f *FeSpotLightTagSvg) Y(value string) *FeSpotLightTagSvg {
	if f.attributes == nil {
		f.attributes = []*Attribute{}
	}
	f.registerAttribute("y", value)
	return f
}

/*
Z -
*/
func (f *FeSpotLightTagSvg) Z(value string) *FeSpotLightTagSvg {
	if f.attributes == nil {
		f.attributes = []*Attribute{}
	}
	f.registerAttribute("z", value)
	return f
}
