// Package tags do not edit, this file was autogenerated.
package tags

import spec "github.com/Nevoral/LuxeGoUI/Specification"

func PathSvg() *PathTagSvg {
	return &PathTagSvg{
		tag: &tag{
			name:                "path",
			attributes:          nil,
			supportedAttributes: nil,
			tagType:             spec.SelfClosingType,
			namespace:           spec.SVG,
			children:            nil,
			textContent:         "",
			parent:              nil,
			nestingLevel:        0,
			renderFormat:        DefaultHtml,
		},
	}
}

type PathTagSvg struct {
	*tag
}

/*
************************************************************************************************************************
*-------------------------------------------------- Extension Method --------------------------------------------------*
************************************************************************************************************************
 */

/*
CustomAttribute - This is method for adding custom attribute, that are not in HTML5 specification.
*/
func (p *PathTagSvg) CustomAttribute(attributes ...*Attribute) *PathTagSvg {
	p.registerAttributes(attributes...)
	return p
}

/*
************************************************************************************************************************
*------------------------------------------------ Specific Attributes -------------------------------------------------*
************************************************************************************************************************
 */

/*
ClipRule -
*/
func (p *PathTagSvg) ClipRule(value string) *PathTagSvg {
	if p.attributes == nil {
		p.attributes = []*Attribute{}
	}
	p.registerAttribute("clip-rule", value)
	return p
}

/*
D -
*/
func (p *PathTagSvg) D(value string) *PathTagSvg {
	if p.attributes == nil {
		p.attributes = []*Attribute{}
	}
	p.registerAttribute("d", value)
	return p
}

/*
Fill -
*/
func (p *PathTagSvg) Fill(value string) *PathTagSvg {
	if p.attributes == nil {
		p.attributes = []*Attribute{}
	}
	p.registerAttribute("fill", value)
	return p
}

/*
FillRule -
*/
func (p *PathTagSvg) FillRule(value string) *PathTagSvg {
	if p.attributes == nil {
		p.attributes = []*Attribute{}
	}
	p.registerAttribute("fill-rule", value)
	return p
}

/*
PathLength -
*/
func (p *PathTagSvg) PathLength(value string) *PathTagSvg {
	if p.attributes == nil {
		p.attributes = []*Attribute{}
	}
	p.registerAttribute("pathLength", value)
	return p
}
