// Package tags do not edit, this file was autogenerated.
package tags

import (
	"fmt"
	spec "github.com/Nevoral/LuxeGoUI/Specification"
)

func PictureHtml(tags []any) *PictureTagHtml {
	node := &PictureTagHtml{
		tag: &tag{
			name:                "picture",
			attributes:          nil,
			supportedAttributes: nil,
			tagType:             spec.FullTagType,
			namespace:           spec.HTML,
			children:            nil,
			textContent:         "",
			parent:              nil,
			nestingLevel:        0,
			renderFormat:        DefaultHtml,
		},
	}
	return node.supportedChildrenCheck(tags)
}

type PictureTagHtml struct {
	*tag
}

/*
************************************************************************************************************************
*-------------------------------------------------- Extension Method --------------------------------------------------*
************************************************************************************************************************
 */

/*
CustomAttribute - This is method for adding custom attribute, that are not in HTML5 specification.
*/
func (p *PictureTagHtml) CustomAttribute(attributes ...*Attribute) *PictureTagHtml {
	p.registerAttributes(attributes...)
	return p
}

/*
Children - Method for nesting tags into parent tag
*/
func (p *PictureTagHtml) Children(tags ...any) *PictureTagHtml {
	return p.supportedChildrenCheck(tags)
}

func (p *PictureTagHtml) supportedChildrenCheck(tags []any) *PictureTagHtml {
	for _, tagObj := range tags {
		switch val := tagObj.(type) {
		case string:
			p.registerChildren(TextContentSvg(val).getTag())
		case content:
			p.registerChildren(val.getTag())
		case []content:
			for _, child := range val {
				p.registerChildren(child.getTag())
			}
		default:
			panic(fmt.Sprintf("Unsupported content type. %v", val))
		}
	}
	return p
}

/*
************************************************************************************************************************
*------------------------------------------------ Specific Attributes -------------------------------------------------*
************************************************************************************************************************
 */
