// Package tags do not edit, this file was autogenerated.
package tags

import (
	"fmt"
	spec "github.com/Nevoral/LuxeGoUI/Specification"
)

func PortalHtml(tags []any) *PortalTagHtml {
	node := &PortalTagHtml{
		tag: &tag{
			name:                "portal",
			attributes:          nil,
			supportedAttributes: nil,
			tagType:             spec.FullTagType,
			namespace:           spec.HTML,
			children:            nil,
			textContent:         "",
			parent:              nil,
			nestingLevel:        0,
			renderFormat:        DefaultHtml,
		},
	}
	return node.supportedChildrenCheck(tags)
}

type PortalTagHtml struct {
	*tag
}

/*
************************************************************************************************************************
*-------------------------------------------------- Extension Method --------------------------------------------------*
************************************************************************************************************************
 */

/*
CustomAttribute - This is method for adding custom attribute, that are not in HTML5 specification.
*/
func (p *PortalTagHtml) CustomAttribute(attributes ...*Attribute) *PortalTagHtml {
	p.registerAttributes(attributes...)
	return p
}

/*
Children - Method for nesting tags into parent tag
*/
func (p *PortalTagHtml) Children(tags ...any) *PortalTagHtml {
	return p.supportedChildrenCheck(tags)
}

func (p *PortalTagHtml) supportedChildrenCheck(tags []any) *PortalTagHtml {
	for _, tagObj := range tags {
		switch val := tagObj.(type) {
		case string:
			p.registerChildren(TextContentSvg(val).getTag())
		case content:
			p.registerChildren(val.getTag())
		case []content:
			for _, child := range val {
				p.registerChildren(child.getTag())
			}
		default:
			panic(fmt.Sprintf("Unsupported content type. %v", val))
		}
	}
	return p
}

/*
************************************************************************************************************************
*------------------------------------------------ Specific Attributes -------------------------------------------------*
************************************************************************************************************************
 */

/*
Referrerpolicy -
*/
func (p *PortalTagHtml) Referrerpolicy(value string) *PortalTagHtml {
	if p.attributes == nil {
		p.attributes = []*Attribute{}
	}
	p.registerAttribute("referrerpolicy", value)
	return p
}

/*
Src - Specifies the URL of an image.
Specifies the URL of an image.
*/
func (p *PortalTagHtml) Src(value string) *PortalTagHtml {
	if p.attributes == nil {
		p.attributes = []*Attribute{}
	}
	p.registerAttribute("src", value)
	return p
}
