// Package tags do not edit, this file was autogenerated.
package tags

import (
	"fmt"
	spec "github.com/Nevoral/LuxeGoUI/Specification"
)

func SelectHtml(tags []any) *SelectTagHtml {
	node := &SelectTagHtml{
		tag: &tag{
			name:                "select",
			attributes:          nil,
			supportedAttributes: nil,
			tagType:             spec.FullTagType,
			namespace:           spec.HTML,
			children:            nil,
			textContent:         "",
			parent:              nil,
			nestingLevel:        0,
			renderFormat:        DefaultHtml,
		},
	}
	return node.supportedChildrenCheck(tags)
}

type SelectTagHtml struct {
	*tag
}

/*
************************************************************************************************************************
*-------------------------------------------------- Extension Method --------------------------------------------------*
************************************************************************************************************************
 */

/*
CustomAttribute - This is method for adding custom attribute, that are not in HTML5 specification.
*/
func (s *SelectTagHtml) CustomAttribute(attributes ...*Attribute) *SelectTagHtml {
	s.registerAttributes(attributes...)
	return s
}

/*
Children - Method for nesting tags into parent tag
*/
func (s *SelectTagHtml) Children(tags ...any) *SelectTagHtml {
	return s.supportedChildrenCheck(tags)
}

func (s *SelectTagHtml) supportedChildrenCheck(tags []any) *SelectTagHtml {
	for _, tagObj := range tags {
		switch val := tagObj.(type) {
		case string:
			s.registerChildren(TextContentSvg(val).getTag())
		case content:
			s.registerChildren(val.getTag())
		case []content:
			for _, child := range val {
				s.registerChildren(child.getTag())
			}
		default:
			panic(fmt.Sprintf("Unsupported content type. %v", val))
		}
	}
	return s
}

/*
************************************************************************************************************************
*------------------------------------------------ Specific Attributes -------------------------------------------------*
************************************************************************************************************************
 */

/*
Autocomplete -
*/
func (s *SelectTagHtml) Autocomplete(value string) *SelectTagHtml {
	if s.attributes == nil {
		s.attributes = []*Attribute{}
	}
	s.registerAttribute("autocomplete", value)
	return s
}

/*
Disabled -
*/
func (s *SelectTagHtml) Disabled() *SelectTagHtml {
	if s.attributes == nil {
		s.attributes = []*Attribute{}
	}
	s.registerAttribute("disabled", "")
	return s
}

/*
Form -
*/
func (s *SelectTagHtml) Form(value string) *SelectTagHtml {
	if s.attributes == nil {
		s.attributes = []*Attribute{}
	}
	s.registerAttribute("form", value)
	return s
}

/*
Multiple -
*/
func (s *SelectTagHtml) Multiple() *SelectTagHtml {
	if s.attributes == nil {
		s.attributes = []*Attribute{}
	}
	s.registerAttribute("multiple", "")
	return s
}

/*
Name -
*/
func (s *SelectTagHtml) Name(value string) *SelectTagHtml {
	if s.attributes == nil {
		s.attributes = []*Attribute{}
	}
	s.registerAttribute("name", value)
	return s
}

/*
Required -
*/
func (s *SelectTagHtml) Required() *SelectTagHtml {
	if s.attributes == nil {
		s.attributes = []*Attribute{}
	}
	s.registerAttribute("required", "")
	return s
}

/*
Size -
*/
func (s *SelectTagHtml) Size(value string) *SelectTagHtml {
	if s.attributes == nil {
		s.attributes = []*Attribute{}
	}
	s.registerAttribute("size", value)
	return s
}
