// Package tags do not edit, this file was autogenerated.
package tags

import spec "github.com/Nevoral/LuxeGoUI/Specification"

func UseSvg() *UseTagSvg {
	return &UseTagSvg{
		tag: &tag{
			name:                "use",
			attributes:          nil,
			supportedAttributes: nil,
			tagType:             spec.SelfClosingType,
			namespace:           spec.SVG,
			children:            nil,
			textContent:         "",
			parent:              nil,
			nestingLevel:        0,
			renderFormat:        DefaultHtml,
		},
	}
}

type UseTagSvg struct {
	*tag
}

/*
************************************************************************************************************************
*-------------------------------------------------- Extension Method --------------------------------------------------*
************************************************************************************************************************
 */

/*
CustomAttribute - This is method for adding custom attribute, that are not in HTML5 specification.
*/
func (u *UseTagSvg) CustomAttribute(attributes ...*Attribute) *UseTagSvg {
	u.registerAttributes(attributes...)
	return u
}

/*
************************************************************************************************************************
*------------------------------------------------ Specific Attributes -------------------------------------------------*
************************************************************************************************************************
 */

/*
Height -
*/
func (u *UseTagSvg) Height(value string) *UseTagSvg {
	if u.attributes == nil {
		u.attributes = []*Attribute{}
	}
	u.registerAttribute("height", value)
	return u
}

/*
Href -
*/
func (u *UseTagSvg) Href(value string) *UseTagSvg {
	if u.attributes == nil {
		u.attributes = []*Attribute{}
	}
	u.registerAttribute("href", value)
	return u
}

/*
Width -
*/
func (u *UseTagSvg) Width(value string) *UseTagSvg {
	if u.attributes == nil {
		u.attributes = []*Attribute{}
	}
	u.registerAttribute("width", value)
	return u
}

/*
X -
*/
func (u *UseTagSvg) X(value string) *UseTagSvg {
	if u.attributes == nil {
		u.attributes = []*Attribute{}
	}
	u.registerAttribute("x", value)
	return u
}

/*
Y -
*/
func (u *UseTagSvg) Y(value string) *UseTagSvg {
	if u.attributes == nil {
		u.attributes = []*Attribute{}
	}
	u.registerAttribute("y", value)
	return u
}
